### ISSUE TITLE
Support of Webhooks

### ISSUE THREAD

**Issue by Smitty010** [marcinziolo/kotlin-wiremock#10]
This isn't a bug.

Have you thought about supporting the wiremock webhook extension?  Any idea how hard that would be to add given the current state of the project?

I realize an issue is that people may not want to include the webhook extension jar.

Any thoughts?

**Comment by checketts** [comment]
This is solved by #19 .  The `withBuilder` allows the underling builder to be exposed and the webhook support is available there.

**Comment by marcinziolo** [comment]
Issue is fixed is 1.0.4
