### ISSUE TITLE
Support static Wiremock 

### ISSUE THREAD

**Issue by Otanikotani** [marcinziolo/kotlin-wiremock#12]
Hello and thank for the awesome library! I have a suggestion for the DSL.

For Junit5 WireMock has an annotation [@WireMockTest](https://wiremock.org/docs/junit-jupiter/) and I am actively using it in my tests. 
The typical test looks like:

```kotlin
...
import com.github.tomakehurst.wiremock.client.WireMock.equalTo
import com.github.tomakehurst.wiremock.client.WireMock.equalToJson
import com.github.tomakehurst.wiremock.client.WireMock.get
import com.github.tomakehurst.wiremock.client.WireMock.okJson
import com.github.tomakehurst.wiremock.client.WireMock.post
import com.github.tomakehurst.wiremock.client.WireMock.stubFor
import com.github.tomakehurst.wiremock.client.WireMock.urlPathEqualTo
import com.github.tomakehurst.wiremock.junit5.WireMockRuntimeInfo
import com.github.tomakehurst.wiremock.junit5.WireMockTest

@WireMockTest(httpPort = 9999)
class CreatorControllerTest {
...

    @Test
    fun `My test`() {
        ... 
        WireMock.stubFor(
             WireMock.post("/some-url")
                .withRequestBody(
                    equalToJson(
                        """
                {
                     some-json
                }
                """
                    )
                )
                .willReturn(
                    okJson(
                        """
                {
                   some-other-json
                }
                """
                    )
                )
        )
        ...
}
```

I really like the DSL of `kotlin-wiremock` but the DSL targets WireMockServer which I don't currently have direct access to in the test. Could we add the extension methods for WireMock as it is currently done for WireMockServer?

**Comment by Otanikotani** [comment]
I have figured out how to do it (more or less) locally, so in case you accept pull requests I can try to make one.

**Comment by marcinziolo** [comment]
hello
yep, please create one and I'll review it. thanks :)

**Comment by Otanikotani** [comment]
https://github.com/marcinziolo/kotlin-wiremock/pull/13 please take a look :)

**Comment by marcinziolo** [comment]
Thanks for pr. I'll look in the evening :)

**Comment by marcinziolo** [comment]
Thanks for the contribution. PR is merged. The new version `1.0.3` is released.
