### ISSUE TITLE
DSL for Wiremock verify API?

### ISSUE THREAD

**Issue by astelmachonak-nydig** [marcinziolo/kotlin-wiremock#15]
Are there any plans or interest for implementing the verify API for Wiremock?

**Comment by marcinziolo** [comment]
Feature added in version: 1.1.0

Please look at examples: https://github.com/marcinziolo/kotlin-wiremock/blob/master/src/test/kotlin/com/marcinziolo/kotlin/wiremock/VerifyTest.kt
