### ISSUE TITLE
Json whole body verification in RequestSpecification

### ISSUE THREAD

**Issue by sergey-volkov-lm** [marcinziolo/kotlin-wiremock#3]
Hello, is there a way to verify the whole request body in wiremock.post { } DSL? I did not find one. I believe it would be very helpful, as soon as request body gets more complex than a set of plain fields.
This feature is present in vanilla WireMock: http://wiremock.org/docs/request-matching/
```java
stubFor(post(urlPathEqualTo("/everything"))
  .withRequestBody(equalToJson("{}"))
  .willReturn(aResponse()));
```

**Comment by marcinziolo** [comment]
Hello @sergey-volkov-lm, 
sorry for the delay I didn't notice the issue.

I added the feature in version `1.0.1`
To verify whole json, look at this:
```kotlin
fun `body equal to`() {
    wiremock.post {
        url equalTo "/hello"
        body equalTo """
            {"pet":"dog"}
        """
    } returnsJson { }

    Given {
        body(//language=JSON
                """
            {"pet":"dog"}
        """
        )
    } When {
        post("$url/hello")
    } Then {
        statusCode(200)
    }
}
```
