### ISSUE TITLE
Support for response body as any object 

### ISSUE THREAD

**Issue by ederfmatos-exacta** [marcinziolo/kotlin-wiremock#34]
### Proposal

It would be interesting to be able to pass an object and have it serialized as json for response

**Comment by leeturner** [comment]
Hi 

Do you mean like the `jsonBody` element in the response:

```json
    "response": {
        "status": 200,
        "jsonBody": {
          "arbitrary_json": [1, 2, 3]
        }
    }
```

https://wiremock.org/docs/stubbing/#specifying-the-response-body

**Comment by leeturner** [comment]
@ederfmatos-exacta I am going to close this issue assuming `jsonBody` is what you were looking for
